name: unet
channels:
    - defaults
dependencies:
    - python=3.10
    - pip=23.3.1
    - pip:
          - ipykernel
          - ipywidgets
          - torch==2.1.2
          - torchvision==0.16.2
          - omegaconf==2.3.0
          - matplotlib=3.8.2
          - timm==0.9.2
          - omegaconf==2.3.0
          - tensorboard==2.15.1
          - seaborn==0.13.2
          - scikit-learn==1.4.0
          - scikit-image==0.22.0
          - opencv-python==4.9.0.80
